### ISSUE TITLE
The add-on is wrongly displayed on the "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [0c0w3/top-sites-experiment#1]
__[Affected Versions]:__
- Dev Edition 69.0b15

__[Affected Platforms]:__
- All Windows
- All Mac
- All Linux

__[Prerequisites]:__
- The "Search Top Sites" [test recipe](https://delivery-console.stage.mozaws.net/recipe/814/) is created and published.

__[Steps to reproduce]:__
1. Open a Developer Edition 69.0b15 profile that can be targeted by the previously set recipe.
2. Navigate to "about:addons" page and observe the "Extensions" section. 

__[Expected results]:__
- The add-on is not displayed in the "about:addons" page.

__[Actual results]:__
- The add-on is displayed.

__[Notes]:__ 
- Please see [mozilla/side-view#385](https://github.com/mozilla/side-view/issues/385#issuecomment-436341881) for more information.
- Please see the following screencast of the issue:

![add-on displayed](https://user-images.githubusercontent.com/26000308/63431200-05b49480-c427-11e9-909e-811fd9a21bc4.gif)

**Comment by 0c0w3** [comment]
Thanks for filing these issues directly on the GitHub! Thanks for linking to mozilla/side-view#385 too. I didn't know about that.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the urlbar-top-sites-experiment@shield.mozilla.org-1.0.0-signed-testing.xpi add-on. Tested on Windows 10 x64, macOS 10.14.6 and Ubuntu 16.04.
