### ISSUE TITLE
Websites from history are displayed inside the drop down instead of Top Sites after restarting the browser

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [0c0w3/top-sites-experiment#2]
__[Affected Versions]:__
- Dev Edition 69.0b15

__[Affected Platforms]:__
- All Windows
- All Mac
- All Linux

__[Prerequisites]:__
- The "Search Top Sites" [test recipe](https://delivery-console.stage.mozaws.net/recipe/814/) is created and published.

__[Steps to reproduce]:__
1. Open a Developer Edition 69.0b15 profile that can be targeted by the previously set recipe.
2. Restart the browser.
3. Navigate to a website (e.g. www.example.com).
4. Click the URL and observe the drop down websites.

__[Expected results]:__
- The Top Sites are displayed in the same order as in the "about:newtab" page.

__[Actual results]:__
- The websites from history are displayed in the drop down.

__[Notes]:__ 
- If you need any advice about the Top Sites section, feel free to follow up with Kate Hudson or Ed Lee since they work on the User Journey page (ex Activity Stream). You can find them on "#fx-messaging-system" slack channel.
- Please see the following screencast of the issue:

![restart history](https://user-images.githubusercontent.com/26000308/63442496-e3794180-c43b-11e9-97f6-d09a3be039f3.gif)

**Comment by 0c0w3** [comment]
Is the add-on still installed when you restart? It looks like it might have been uninstalled but didn't clean up the pref it set to open the urlbar view on focus.

If it does remain installed on restart, then after restart, could you please open the browser console, check the "Show Content Messages" checkbox, and let me know about any messages?

**Comment by 0c0w3** [comment]
To be specific, the kinds of browser console messages I'm looking for are:

* Start with "urlbar-top-sites-experiment@shield.mozilla.org"
* "isTemporaryInstall=X study=X"
* Any errors and warnings

**Comment by SoftVision-CarmenFat** [comment]
Yes, the add-on remains installed and the user is not unenrolled from the experiment. I can still trigger the "engagement" and "abandonment" events in "about:telemetry#events-tab" page. Also, the experiment is still displayed as active in "about:studies" page.

I've looked in the Browser Console **_after restarting_** the browser but was unable to find anything you mentioned in the previous comment. However, I think it would be better to show you all the log from the Browser Console after the restart.


![after restart](https://user-images.githubusercontent.com/26000308/63493830-1b789700-c4c5-11e9-85a0-1abd2157f3e2.png)


I don't know if this is helpful, but **_before the restart_**, I've noticed there is a message regarding the TemporaryInstall:

```
isTemporaryInstall=false study=[object Object] background.js:173:11
urlbar-top-sites-experiment@shield.mozilla.org enrolled background.js:22:11
urlbar-top-sites-experiment@shield.mozilla.org ready background.js:22:11
```


![before restart](https://user-images.githubusercontent.com/26000308/63493866-321eee00-c4c5-11e9-8ce8-29be9050e3dc.png)


Please let me know if you need more details.

**Comment by 0c0w3** [comment]
OK, I can reproduce this, and I think I see the problem. The add-on is waiting for an `onInstalled` message that never comes because after restart, the add-on is considered to be already installed.

**Comment by 0c0w3** [comment]
I attached a new unsigned xpi to the bug and asked mythmon to sign it for testing. Please keep an eye on that bug for him to post the new signed xpi. It should be fixed now.

**Comment by 0c0w3** [comment]
The bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1547670

**Comment by 0c0w3** [comment]
The xpi is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1547670#c24

Direct link: https://bugzilla.mozilla.org/attachment.cgi?id=9088230

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the urlbar-top-sites-experiment@shield.mozilla.org-1.0.0-signed-testing.xpi add-on. Tested on Windows 10 x64, macOS 10.14.6 and Ubuntu 16.04.
