### ISSUE TITLE
The order of the Search Shortcuts inside the drop down doesn't correspond with the order from the new tab page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [0c0w3/top-sites-experiment#3]
__[Affected Versions]:__
- Dev Edition 69.0b15

__[Affected Platforms]:__
- All Windows
- All Mac
- All Linux

__[Prerequisites]:__
- The "Search Top Sites" [test recipe](https://delivery-console.stage.mozaws.net/recipe/814/) is created and published.

__[Steps to reproduce]:__
1. Open a Developer Edition 69.0b15 profile that can be targeted by the previously set recipe.
2. Navigate to a website (e.g. www.example.com).
3. Click the URL and observe the drop down websites.

__[Expected results]:__
- The Top Sites are displayed in the same order as in the "about:newtab" page.

__[Actual results]:__
- The Amazon Search Shortcut is placed first in the Top Sites list.

__[Notes]:__ 
- This issue is also reproducible with other Search Shortcuts.
- Please see the following screencast of the issue:

![search shortcut](https://user-images.githubusercontent.com/26000308/63444532-736cba80-c43f-11e9-973b-dcc466de72ea.gif)

**Comment by 0c0w3** [comment]
We're going to have to live with this one, at least for the experiment's initial rollout in 69.

This is due to the sorting that `UrlbarMuxerUnifiedComplete` does, in the product. It's not something the add-on can change. It sorts search results, which includes keyword offers, above (most) everything else.

**Comment by 0c0w3** [comment]
I'm going to close these wontfix bugs so they get off my dashboard. Thanks for filing them though. For this particular one, we have a corresponding Bugzilla bug for fixing it in the product iirc (the ability for extensions to define their own muxers).

**Comment by 0c0w3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1547287 is the bug. I added a comment there about this issue.
