### ISSUE TITLE
The Add-on is not removed after its expiration date

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [0c0w3/top-sites-experiment#4]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Developer Edition 69.0b15, Build ID 20190819184224

[Prerequisites]:
- Have the urlbar-top-sites-experiment@shield.mozilla.org-1.0.0-signed-testing.xpi add-on installed using Normandy.
- Have the xpinstall.signatures.dev-root boolean preference set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Change the system time to 60 days in the future.
3. Restart the browser and observe the behavior.

[Expected result]:
- The add-on is removed.

[Actual result]:
- The add-on remains installed.

[Notes]:
- This issue is reproducible with the control and treatment branches of the study.
- I have attached a screen recording of the issue:
![expiration](https://user-images.githubusercontent.com/40393891/63513308-7ecaef00-c4ee-11e9-9c57-7ec97e84961a.gif)

**Comment by 0c0w3** [comment]
The add-on doesn't control when/how it gets uninstalled at the end of the study. That's handled by the Normandy component inside Firefox. So if this is actually a bug, it's a bug in Normandy. I have a hard time believing it's actually a bug though because we've run many experiments before this one. But this is the first new-style Normandy study, so maybe that's related.

Is it possible for you to try this with some other experiment and add-on?

**Comment by 0c0w3** [comment]
OK, I talked with mythmon about this. This is in fact a difference between old-style studies and new-style studies. New-style studies like this one must be manually disabled using the Delivery Console. You need to disable the recipe. After that, he says you need to trigger Normandy to run again in Firefox -- usually for QA that just means to restart Firefox.

Please let me know whether that works or you have any questions about it.

**Comment by Softvision-PatriciuPop** [comment]
Old-style experiments were handled in the same way by Normandy when it came to expiration. However in the past we didn't have access to Normandy or any other way to test add-on expiration after a set period of time, so add-ons removing themselves was an extra precaution to make sure that users wouldn't remain stuck in experiments if anything happened with Normandy (See bug [1473874](https://bugzilla.mozilla.org/show_bug.cgi?id=1473874) and bug [1518417](https://bugzilla.mozilla.org/show_bug.cgi?id=1518417)).

Our team has since started testing the Normandy feature as well and we perform weekly checks to make sure recipe functionality is unaffected. We now have a way to test various expiration scenarios in a Stage environment. We could drop this precaution of add-ons to handling their own expiration since we could test this using recipes, but this would mean our team would need to have a discussion and see if the risk is worth it. For now, we’d prefer to still have the fallback if possible.

**Comment by 0c0w3** [comment]
Marking this wontfix as discussed over email.

**Comment by 0c0w3** [comment]
I'm going to close these wontfix bugs so they get off my dashboard. Thanks for filing them though.
