### ISSUE TITLE
The Top Sites drop down is not triggered if the address bar is focused using the "Tab" key

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [0c0w3/top-sites-experiment#5]
__[Affected Versions]:__
- Dev Edition 69.0b15

__[Affected Platforms]:__
- All Windows
- All Mac
- All Linux

__[Prerequisites]:__
- The "Search Top Sites" [test recipe](https://delivery-console.stage.mozaws.net/recipe/814/) is created and published.

__[Steps to reproduce]:__
1. Open a Developer Edition 69.0b15 profile that can be targeted by the previously set recipe.
2. Navigate to a website (e.g. www.example.com).
3. Press the "Tab" key until the address bar is focused.
4. Observe the behavior.

__[Expected results]:__
- The Top Sites drop down is displayed.

__[Actual results]:__
- Nothing happens, the Top Sites drop down is not triggered.

__[Notes]:__ 
- The drop down containing websites from history is displayed if pressing the "Space" key after focusing the URL bar with "Tab" key.
- Please see the following screencast of the issue:

![Tab key](https://user-images.githubusercontent.com/26000308/63516682-1c75ec80-c4f6-11e9-8ac4-1aade6c9894d.gif)

**Comment by 0c0w3** [comment]
This is a known issue, unfortunately. Fixing it requires modifications to Firefox itself, and that's too late for 69 now, so we'll have to live with it for 69.

**Comment by 0c0w3** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1575957 so we don't forget about this.

**Comment by 0c0w3** [comment]
I'm going to close these wontfix bugs so they get off my dashboard. Thanks for filing them though.
