### ISSUE TITLE
The Top Sites drop down is not triggered anymore if an empty tile is placed between the populated ones in the new tab page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [0c0w3/top-sites-experiment#6]
__[Affected Versions]:__
- Dev Edition 69.0b15

__[Affected Platforms]:__
- All Windows
- All Mac
- All Linux

__[Prerequisites]:__
- The "Search Top Sites" [test recipe](https://delivery-console.stage.mozaws.net/recipe/814/) is created and published.

__[Steps to reproduce]:__
1. Open a Developer Edition 69.0b15 profile that can be targeted by the previously set recipe.
2. Open a new tab.
3. Drag and drop any populated tile and place it at the end of the row.
4. Navigate to a website and click the address bar.
5. Observe what happens next.

__[Expected results]:__
- The Top Sites drop down is displayed.

__[Actual results]:__
- Nothing happens, the Top Sites drop down is not triggered.

__[Notes]:__ 
- Since this issue only happens to new profiles, we might want to add a condition to the final recipe in order to filter out new profiles.
- Please see the following screencast of the issue:

![empty tile](https://user-images.githubusercontent.com/26000308/63520997-4a5f2f00-c4fe-11e9-8ba1-2bd9bb1fb0a5.gif)

**Comment by 0c0w3** [comment]
Nice catch! Thanks.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the urlbar-top-sites-experiment@shield.mozilla.org-1.0.0-signed-testing.xpi add-on. Tested on Windows 10 x64, macOS 10.14.6 and Ubuntu 16.04.
