### ISSUE TITLE
"engagement" and "abandonment" events are sent still sent after the Browser is restarted in Safe Mode

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [0c0w3/top-sites-experiment#7]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Dev Edition 69.0b17, Build ID 20190826143733

[Prerequisites]:
- Have the "xpinstall.signatures.dev-root" boolean preference set to "true".
- Have the "security.content.signature.root_hash" pref set to "DB:74:CE:58:E4:F9:D0:9E:E0:42:36:BE:6C:C5:C4:F6:6A:E7:74:7D:C0:21:42:7A:03:BC:2F:57:0C:8B:9B:90".
- Have the "app.normandy.api_url" pref set to "https://stage.normandy.nonprod.cloudops.mozgcp.net/api/v1".
- Have the "app.normandy.dev_mode" pref set to "true".
- Have the "app.normandy.logging.level" pref set to "0".
- Have the "services.settings.server" pref set to "https://settings.stage.mozaws.net/v1".
- Have the "carmen-treatment" boolean pref set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and ensure you are enrolled in the "urlbar-top-sites-experiment-treatment" study.
2. Restart the browser in Safe Mode and navigate to a website.
3. Click the address bar and press the "Esc" key.
4. Navigate to about:telemetry and click the "Events" button.
5. Observe the events section.

[Expected result]:
- No urlbar specific events are displayed.

[Actual result]:
- An "abandonment" event is sent.

[Notes]:
- Although bug [1576246](https://bugzilla.mozilla.org/show_bug.cgi?id=1576246) has landed, and "browser.urlbar.eventTelemetry.enabled" is present by default, the issue is still reproducible.
- The issue is also reproducible when you engage with a top site in the drop down and trigger the "engagement" event.
- I have attached a screen recording of the issue:
![STS_safe_mode](https://user-images.githubusercontent.com/40393891/63773764-88849600-c8e4-11e9-9125-cc1ada54e64a.gif)

**Comment by 0c0w3** [comment]
Thanks. This looks like a bug in the webextensions framework in Firefox. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1576997. It's too late to try to fix this for 69, and I think it's fine to ship the experiment with this bug because I don't expect many users will hit it. I will bring it up with the rest of the team to see what they think, though.

So for now I'll mark this as wontfix and close it.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the urlbar-top-sites-experiment@shield.mozilla.org-1.0.0-signed.xpi add-on. Tested on Windows 10 x64, macOS 10.14.6 and Ubuntu 16.04.
